sudo: required
language: go
go_import_path: github.com/taoblockchain/tao2

env:
  global:
    - GOPROXY=https://proxy.golang.org
    - GO111MODULE=on


jobs:
  include:

  - stage: Lint
    sudo: false
    go: '1.13.x'
    git:
      submodules: false
      script:
        - go run build/ci.go lint

  - stage: Github release
    go: '1.12.x'
    script:
      - make tao-cross
    deploy:
      provider: releases
      api_key: $GITHUB_TOKEN
      overwrite: true
      file_glob: true
      file: build/bin/tao-*
      skip_cleanup: true
      on:
        tags: true

  - stage: Build and push image
    services:
      - docker
    install: skip
    before_script:
      - docker build -t taoblockchain/tao2 .
      - docker build -t taoblockchain/node -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag taoblockchain/tao2 taoblockchain/tao2:latest
      - docker push taoblockchain/tao2:latest
      - docker tag taoblockchain/tao2 taoblockchain/tao2:$TRAVIS_BUILD_ID
      - docker push taoblockchain/tao2:$TRAVIS_BUILD_ID
      - docker tag taoblockchain/node taoblockchain/node:latest
      - docker push taoblockchain/node:latest
      - docker tag taoblockchain/node taoblockchain/node:$TRAVIS_BUILD_ID
      - docker push taoblockchain/node:$TRAVIS_BUILD_ID

  - stage: Build and push image (tagged)
    services:
      - docker
    install: skip
    before_script:
      - docker build -t taoblockchain/tao2 .
      - docker build -t taoblockchain/node -f Dockerfile.node .
    script:
      - echo "$DOCKER_PASSWORD" | docker login --username "$DOCKER_USERNAME" --password-stdin
      - docker tag taoblockchain/tao2 taoblockchain/tao2:latest
      - docker push taoblockchain/tao2:latest
      - docker tag taoblockchain/tao2 taoblockchain/tao2:$TRAVIS_TAG
      - docker push taoblockchain/tao2:$TRAVIS_TAG
      - docker tag taoblockchain/tao2 taoblockchain/node:latest
      - docker push taoblockchain/node:latest
      - docker tag taoblockchain/node taoblockchain/node:$TRAVIS_TAG
      - docker push taoblockchain/node:$TRAVIS_TAG

stages:
  - name: Lint
  - name: Build and test
  - name: Github release
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = taoblockchain/tao2
  - name: Build and push image
    if: type != pull_request AND branch = master AND tag IS blank AND repo = taoblockchain/tao2
  - name: Build and push image (tagged)
    if: type != pull_request AND branch =~ ^v AND tag IS present AND repo = taoblockchain/tao2

